name: Java CI with Maven

on:
  push:
    branches: [ "SolutionP8" ]
  pull_request:
    branches: [ "SolutionP8" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      #  On se place dans le bon dossier (TourGuide).
      - name: Move into TourGuide directory
        run: cd TourGuide

      #  Installation des JAR locaux
      - name: Install TourGuide local JAR dependencies
        working-directory: TourGuide
        run: |
          mvn install:install-file -Dfile=libs/gpsUtil.jar -DgroupId=gpsUtil -DartifactId=gpsUtil -Dversion=1.0.0 -Dpackaging=jar
          mvn install:install-file -Dfile=libs/TripPricer.jar -DgroupId=tripPricer -DartifactId=tripPricer -Dversion=1.0.0 -Dpackaging=jar
          mvn install:install-file -Dfile=libs/RewardCentral.jar -DgroupId=rewardCentral -DartifactId=rewardCentral -Dversion=1.0.0 -Dpackaging=jar

      # Build Maven with tests + JaCoCo
      - name: Build with Maven (tests + JaCoCo)
        working-directory: TourGuide
        run: mvn -B clean verify

      - name: Upload artifacts (JAR + test reports + coverage))
        uses: actions/upload-artifact@v4
        with:
          name: tourguide-artifacts
          path: |
            TourGuide/target/*.jar
            TourGuide/target/surefire-reports/
            TourGuide/target/site/jacoco/